return {
	AmbientLight = require("rat-scratch-pipeline.AmbientLight"),
	AnimationPipeline = require("rat-scratch-pipeline.AnimationPipeline"),
	ArcballCamera = require("rat-scratch-pipeline.ArcballCamera"),
	Buffer = require("rat-scratch-pipeline.Buffer"),
	Camera = require("rat-scratch-pipeline.Camera"),
	DrawPipeline = require("rat-scratch-pipeline.DrawPipeline"),
	GLTF = require("rat-scratch-pipeline.GLTF"),
	IndexBufferInfo = require("rat-scratch-pipeline.IndexBufferInfo"),
	Light = require("rat-scratch-pipeline.Light"),
	LightEvent = require("rat-scratch-pipeline.LightEvent"),
	MaterialPipeline = require("rat-scratch-pipeline.MaterialPipeline"),
	MeshletFormat = require("rat-scratch-pipeline.MeshletFormat"),
	ObjectHandle = require("rat-scratch-pipeline.ObjectHandle"),
	ObjectHandleAnimatorProvider = require(
		"rat-scratch-pipeline.ObjectHandleAnimatorProvider"
	),
	ObjectHandleEvent = require("rat-scratch-pipeline.ObjectHandleEvent"),
	ObjectPipeline = require("rat-scratch-pipeline.ObjectPipeline"),
	PipelineConfig = require("rat-scratch-pipeline.PipelineConfig"),
	PipelineRuntime = require("rat-scratch-pipeline.PipelineRuntime"),
	PointLight = require("rat-scratch-pipeline.PointLight"),
	Resources = require("rat-scratch-pipeline.Resources"),
	Scene = require("rat-scratch-pipeline.Scene"),
	SpotLight = require("rat-scratch-pipeline.SpotLight"),
	Utility = require("rat-scratch-pipeline.Utility"),
	VertexBufferInfo = require("rat-scratch-pipeline.VertexBufferInfo"),
	World = require("rat-scratch-pipeline.World"),
}
