return {
	AmbientLight = require("rat-scratch-pipeline.AmbientLight"),
	AnimationPipeline = require("rat-scratch-pipeline.AnimationPipeline"),
	ArcballCameraView = require("rat-scratch-pipeline.ArcballCameraView"),
	Buffer = require("rat-scratch-pipeline.Buffer"),
	Camera = require("rat-scratch-pipeline.Camera"),
	CameraEvent = require("rat-scratch-pipeline.CameraEvent"),
	CameraFrame = require("rat-scratch-pipeline.CameraFrame"),
	CameraProjection = require("rat-scratch-pipeline.CameraProjection"),
	CameraView = require("rat-scratch-pipeline.CameraView"),
	DirectionalLight = require("rat-scratch-pipeline.DirectionalLight"),
	Draw = require("rat-scratch-pipeline.Draw"),
	DrawPipeline = require("rat-scratch-pipeline.DrawPipeline"),
	GLTF = require("rat-scratch-pipeline.GLTF"),
	Graphics3D = require("rat-scratch-pipeline.Graphics3D"),
	IndexBufferInfo = require("rat-scratch-pipeline.IndexBufferInfo"),
	Light = require("rat-scratch-pipeline.Light"),
	LightClusterResult = require("rat-scratch-pipeline.LightClusterResult"),
	LightEvent = require("rat-scratch-pipeline.LightEvent"),
	LightPipeline = require("rat-scratch-pipeline.LightPipeline"),
	MaterialPipeline = require("rat-scratch-pipeline.MaterialPipeline"),
	MeshletFormat = require("rat-scratch-pipeline.MeshletFormat"),
	ModelInstancesHandle = require("rat-scratch-pipeline.ModelInstancesHandle"),
	ModelPipeline = require("rat-scratch-pipeline.ModelPipeline"),
	ObjectHandle = require("rat-scratch-pipeline.ObjectHandle"),
	ObjectHandleAnimatorProvider = require(
		"rat-scratch-pipeline.ObjectHandleAnimatorProvider"
	),
	ObjectHandleEvent = require("rat-scratch-pipeline.ObjectHandleEvent"),
	ObjectPipeline = require("rat-scratch-pipeline.ObjectPipeline"),
	PerspectiveFOVCameraProjection = require(
		"rat-scratch-pipeline.PerspectiveFOVCameraProjection"
	),
	Pipelines = require("rat-scratch-pipeline.Pipelines"),
	PipelineConfig = require("rat-scratch-pipeline.PipelineConfig"),
	PipelineRuntime = require("rat-scratch-pipeline.PipelineRuntime"),
	PipelineRenderer = require("rat-scratch-pipeline.PipelineRenderer"),
	PipelineProperty = require("rat-scratch-pipeline.PipelineProperty"),
	PipelineSetting = require("rat-scratch-pipeline.PipelineSetting"),
	PipelineSettingPreset = require(
		"rat-scratch-pipeline.PipelineSettingPreset"
	),
	PointLight = require("rat-scratch-pipeline.PointLight"),
	Resources = require("rat-scratch-pipeline.Resources"),
	Scene = require("rat-scratch-pipeline.Scene"),
	SpotLight = require("rat-scratch-pipeline.SpotLight"),
	Utility = require("rat-scratch-pipeline.Utility"),
	VertexBufferInfo = require("rat-scratch-pipeline.VertexBufferInfo"),
	World = require("rat-scratch-pipeline.World"),
}
